// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwRrhJUz4UDcPuvwkrv1wXZGagyeRkImU',
    appId: '1:867906297948:web:1704ea8c1ea74eb277c699',
    messagingSenderId: '867906297948',
    projectId: 'flutter-app-1b03a',
    authDomain: 'flutter-app-1b03a.firebaseapp.com',
    storageBucket: 'flutter-app-1b03a.appspot.com',
    measurementId: 'G-Y2FZ3WDZ1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXgQLtwkxR0QEZb3zW9EAL_cmg0u6Zttw',
    appId: '1:867906297948:android:20438c9813e0b9d477c699',
    messagingSenderId: '867906297948',
    projectId: 'flutter-app-1b03a',
    storageBucket: 'flutter-app-1b03a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEdgvQUxUBGRoZZrVlANyk-RpHhMGLh2Y',
    appId: '1:867906297948:ios:ce1136ebfdc03a0f77c699',
    messagingSenderId: '867906297948',
    projectId: 'flutter-app-1b03a',
    storageBucket: 'flutter-app-1b03a.appspot.com',
    iosBundleId: 'com.example.countertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEdgvQUxUBGRoZZrVlANyk-RpHhMGLh2Y',
    appId: '1:867906297948:ios:fa1840ac9e49711677c699',
    messagingSenderId: '867906297948',
    projectId: 'flutter-app-1b03a',
    storageBucket: 'flutter-app-1b03a.appspot.com',
    iosBundleId: 'com.example.countertest.RunnerTests',
  );
}
